# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jacopo Grilli
email: grilli.jacopo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: 
#url: "http://home.uchicago.edu/~jgrilli/"
url: "https://jacopogrilli.github.io"

# other info
twitter_username: jacrickets
#github_username:  jacopogrilli
scholar_username: "P2V3b3QAAAAJ"
resgate_username: "Jacopo_Grilli"
orcid_username: "0000-0002-8235-5803"
publons_username: "558637"
arxiv_username: "grilli_j_1"
biorxiv_username: "jacopo grilli"
linkedin_username: "jacopo-grilli/a6/9b9/15a/en"
mendeley_username: "jacopo-grilli"
maplocation: Santa+Fe+Institute
author: "Jacopo Grilli"


map_latitude: 35.700000
map_longitude: -105.90855 
map_title: 'Santa Fe Institute'
map_apikey: "AIzaSyD3OqSEPg5iyHcriIfz-776IahCE3DhxZY"

include:
  - .htaccess
  - _pages




sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

